
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "bank", targetNamespace = "http://banque/", wsdlLocation = "http://localhost:2020/?wsdl")
public class Bank
    extends Service
{

    private static final URL BANK_WSDL_LOCATION;
    private static final WebServiceException BANK_EXCEPTION;
    private static final QName BANK_QNAME = new QName("http://banque/", "bank");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:2020/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANK_WSDL_LOCATION = url;
        BANK_EXCEPTION = e;
    }

    public Bank() {
        super(__getWsdlLocation(), BANK_QNAME);
    }

    public Bank(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANK_QNAME, features);
    }

    public Bank(URL wsdlLocation) {
        super(wsdlLocation, BANK_QNAME);
    }

    public Bank(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANK_QNAME, features);
    }

    public Bank(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Bank(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BanqueService
     */
    @WebEndpoint(name = "banqueServicePort")
    public BanqueService getBanqueServicePort() {
        return super.getPort(new QName("http://banque/", "banqueServicePort"), BanqueService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BanqueService
     */
    @WebEndpoint(name = "banqueServicePort")
    public BanqueService getBanqueServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://banque/", "banqueServicePort"), BanqueService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANK_EXCEPTION!= null) {
            throw BANK_EXCEPTION;
        }
        return BANK_WSDL_LOCATION;
    }

}
