
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "banqueService", targetNamespace = "http://banque/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversion", targetNamespace = "http://banque/", className = "proxy.Conversion")
    @ResponseWrapper(localName = "conversionResponse", targetNamespace = "http://banque/", className = "proxy.ConversionResponse")
    @Action(input = "http://banque/banqueService/conversionRequest", output = "http://banque/banqueService/conversionResponse")
    public double conversion(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getlistcompte", targetNamespace = "http://banque/", className = "proxy.Getlistcompte")
    @ResponseWrapper(localName = "getlistcompteResponse", targetNamespace = "http://banque/", className = "proxy.GetlistcompteResponse")
    @Action(input = "http://banque/banqueService/getlistcompteRequest", output = "http://banque/banqueService/getlistcompteResponse")
    public List<Compte> getlistcompte();

    /**
     * 
     * @param arg0
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getcompte", targetNamespace = "http://banque/", className = "proxy.Getcompte")
    @ResponseWrapper(localName = "getcompteResponse", targetNamespace = "http://banque/", className = "proxy.GetcompteResponse")
    @Action(input = "http://banque/banqueService/getcompteRequest", output = "http://banque/banqueService/getcompteResponse")
    public Compte getcompte(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
